---
- hosts: all
  become: true
  vars:
    ansible_user: ec2-user
  tasks:
    - name: Wait for connection to be ready
      wait_for_connection:
        delay: 5
        timeout: 300
    - name: Update apt cache
      yum:
        name: '*'
        state: latest
    - name: Install Docker
      yum:
        name: docker
        state: latest
    - name: Instalar Python3
      become: false
      yum:
        name: python3
        state: present
    - name: Instalar Docker Compose
      become: false
      pip:
        name: docker-compose
        state: present
    - name: Copy local directory to remote server
      copy:
        src: "docker-compose.yaml"
        dest: "/home/ec2-user/"
        owner: ec2-user
        group: ec2-user
        mode: 0755
    