---
- hosts: all
  become: true
  vars:
    ansible_user: ec2-user
  tasks:
    - name: Wait for connection to be ready
      wait_for_connection:
        delay: 30
        sleep: 5
        timeout: 300
    - name: Update apt cache
      yum:
        name: '*'
        state: latest
    - name: Install Docker
      yum:
        name: docker
        state: latest
    - name: Inicio Docker
      service:
        name: docker
        state: started
    - name: Habilitar servicio de Docker
      systemd:
        name: docker
        enabled: yes
    - name: Instalar Python3
      become: false
      yum:
        name: python
        state: latest
    - name: Instalar Docker Compose
      command: "pip3 install docker-compose"
    - name: Copy local directory to remote server
      copy:
        src: "../docker-compose.yaml"
        dest: "/home/ec2-user/"
        owner: ec2-user
        group: ec2-user
        mode: 0755
    - name: Cambios de permisos
      command: "usermod -aG docker ec2-user"
    - name: Descarga de imagen
      become: false
      command: "docker pull ghcr.io/edugoma/hello-terraform:latest "
    - name: Deploy imagen
      become: false
      command: "docker-compose up -d"
    