---
- hosts: all
  become: true
  gather_facts: false
  vars:
    ansible_user: ec2-user
  tasks:
    - name: Wait for connection to be ready
      wait_for_connection:
        delay: 30
        sleep: 5
        timeout: 300  
    - name: Instalar Docker
      yum:
        name: docker
        state: present
        update_cache: yes
    - name: Inicio Docker
      service:
        name: docker
        state: started
        enabled: true       
    - name: add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: true    
    - name: Instalar Docker Compose
      pip:
        name: docker-compose>1.7.0,<2.0.0
        executable: pip3
      become: false
    - name: Copy local directory to remote server
      copy:
        src: "./docker-compose.yaml"
        dest: "/home/ec2-user/"
        owner: ec2-user
        group: ec2-user
        mode: 0744
    #- name: Descarga de imagen
      #command: "docker pull ghcr.io/edugoma/hello-terraform:latest "
    - name: Ejecutar docker-compose up
      docker_compose:
        project_src: /home/ec2-user
        pull: true   
      vars:
        ansible_python_interpreter: /usr/bin/python3
      #command: docker-compose -f /home/ec2-user/docker-compose.yaml up -d
    