---
- hosts: all
  become: true
  vars:
    ansible_user: ec2-user
  tasks:
    - name: Wait for connection to be ready
      wait_for_connection:
        delay: 5
        timeout: 300
    - name: Install Docker
      yum:
        name: docker
        state: latest