---
- hosts: all
  become: true
  gather_facts: false
  vars:
    ansible_user: ec2-user
  tasks:
    - name: Wait for connection to be ready
      wait_for_connection:
        delay: 30
        sleep: 5
        timeout: 300
    - name: Instalar Docker
      yum:
        name: docker
        state: latest
    - name: Inicio Docker
      service:
        name: docker
        state: started
        enabled: true   
    - name: installar python
      yum:
        name: python
        state: latest 
    - name: Instalar Docker Compose
      pip:
        name: docker-compose
        executable: pip3
    - name: Instalar libreria docker
      pip:
        name: docker
        executable: pip3
    - name: Copy local directory to remote server
      copy:
        src: "./docker-compose.yaml"
        dest: "/home/ec2-user/"
        owner: ec2-user
        group: ec2-user
        mode: 0755
    - name: add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: true
    - name: Descarga de imagen
      command: "docker pull ghcr.io/edugoma/hello-terraform:latest "
    - name: Ejecutar docker-compose up --no-build
      #become_user: ec2-user chdir=/home/ec2-user/
      command: docker-compose up -d
    #- name: Run docker-compose up
      #become: false
      #shell: 
        #cmd: cd /home/ec2-user/
        #cmd: docker-compose --no-build -d
      #docker_compose:
        #recreate: never
        #project_src: flask
      #register: output
    